### ISSUE TITLE
New Codelist - Quality Report Type

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdCodes#39]
Relative to implementing ISO 19157 Data Quality add an ADIwg codelist identifying Data Quality Element reports.

- Name: adiwg_qualityReportType
- Source: Alaska Data Integration working group
- Source Name: ADIwg_QualityReportType
- Description: the type of quality report
---
Code: 001
Code Name: completenessCommission
Description: excess data present in a data set

Code: 002
Code Name: completenessOmission
Description: data absent from a data set

Code: 003
Code Name: conceptualConsistency
Description: adherence to rules of the conceptual schema

Code: 004
Code Name: domainConsistency
Description: adherence of values to the value domains

Code: 005
Code Name: formatConsistency
Description: degree to which data are stored in accordance with the physical structure of
the data set

Code: 006
Code Name: topologicalConsistency
Description: correctness of the explicitly encoded topological characteristics of a data set

Code: 007
Code Name: absoluteExternalPositionalAccuracy
Description: closeness of reported coordinate values to values accepted as or
being true

Code: 008
Code Name: relativeInternalPositionalAccuracy
Description: closeness of the relative positions of features in a data set to their
respective relative positions accepted as or being true

Code: 009
Code Name: griddedDataPositionalAccuracy
Description: closeness of gridded data spatial position values to values accepted
as or being true

Code: 010
Code Name: thematicClassificationCorrectness
Description: comparison of the classes assigned to features or their attributes to a
universe of discourse (e.g. ground truth or reference data);

Code: 011
Code Name: thematicNonQuantativeAttributeCorrectness
Description: measure of whether a non-quantitative attribute is correct
or incorrect

Code: 012
Code Name: thematicQuantitativeAttributeAccuracy
Description: closeness of the value of a quantitative attribute to a value accepted
as or known to be true

Code: 013
Code Name: thematicAccuracyOfATimeMeasurement
Description: closeness of reported time measurements to values accepted as or
known to be true

Code: 014
Code Name: temporalConsistency
Description: correctness of the order of events

Code: 015
Code Name: temporalValidity
Description: validity of data with respect to time

Code: 016
Code Name: usabilityElement
Description: describes specific quality information about a data set’s suitability for a particular application or conformance to a set of requirements not defined in the standard quality reports

Code: 017
Code Name: metaqualityConfidence
Description: trustworthiness of a data quality result

Code: 018
Code Name: metaqualityRepresentativity
Description: degree to which the sample used has produced a result which is representative of the data within the data quality scope

Code: 019
Code Name: metaqualityHomogeneity
Description: expected or tested uniformity of the results obtained for a data quality evaluation

**Comment by hmaier-fws** [comment]
@dwalt @jwaspin Can this issue be closed?

The list seems to be the same as the current [adiwg_dataQualityElement](https://github.com/adiwg/mdCodes/blob/develop/resources/adiwg_dataQualityElement.yml) which has a PR #89 that will revert the codes back to using the DQ_ prefix. I don't recall if we were just going to use the DQ element class names in both the editor and translator, or if we were going to have a second code list for use in the mdEditor picklist.

There are a few differences between this list and the current one, but **I'm assuming that is because of an update to the standard**:
  - current codes for NonQuantativeAttributeCorrectness,  QuantitativeAttributeAccuracy, and AccuracyOfATimeMeasurement, are not prefixed with "thematic" as shown above
  - temporalConsistency seems to have been replaced by TemporalValidity
  - usabilityElement, metaqualityConfidence, metaqualityRepresentativity, and metaqualityHomogeneity are not in the current list

**Comment by jwaspin** [comment]
@hmaier-fws I'll defer to @dwalt for this list being exactly correct, but I can at least mention that this one has gone back and forth a little bit. We decided to leave the DQ_ prefix for now because moving to the newer names was complicating things and it might need more than just the name change (the tags looked different to me, but I could have misread it). This final list is intended to work directly with the iso-3 writer, which uses the code list to generate the tag, which is also part of the complication in modifying this list.

**Comment by jwaspin** [comment]
Closing this because we have the list, if we need to fix it at any point then we should create a new issue
